USE [master]
GO

/****** Object:  Database [AttivitàManutenzione]    Script Date: 13/06/2023 11:02:02 ******/
CREATE DATABASE [AttivitàManutenzione]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AttivitàManutenzione', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AttivitàManutenzione.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AttivitàManutenzione_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AttivitàManutenzione_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AttivitàManutenzione].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AttivitàManutenzione] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET ARITHABORT OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AttivitàManutenzione] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AttivitàManutenzione] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AttivitàManutenzione] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AttivitàManutenzione] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AttivitàManutenzione] SET  MULTI_USER 
GO

ALTER DATABASE [AttivitàManutenzione] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AttivitàManutenzione] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AttivitàManutenzione] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AttivitàManutenzione] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AttivitàManutenzione] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AttivitàManutenzione] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AttivitàManutenzione] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AttivitàManutenzione] SET  READ_WRITE 
GO

